before_script:
   - npm install -g gulp
language: node_js
node_js:
  - "7"
script: gulp build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  acl: public_read
  region: eu-central-1
  before_deploy: "mv -R res deploy/. && mv -R src deploy/. && mv -R test deploy/."
  local_dir: deploy
  on:
    branch: master
    tags: true