name: build and deploy(chrome)

on:
  push:
#    branches:
#      - master
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        target: [ "chrome", "firefox" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build:${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.target }}
          path: dist-${{ matrix.target }}/

  deploy-chrome:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-chrome
      - run: zip -r plussub.zip .
      - run: >
          curl "https://accounts.google.com/o/oauth2/token"
          -d "client_id=${{CHROME_CLIENT_ID}}&client_secret=${{CHROME_CLIENT_SECRET}}&code=${{CHROME_CODE_TOKEN}}&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob" > resp.json
      - run: cat resp.json
#      - run: >
#          curl -H "Authorization: Bearer $TOKEN"
#          -H "x-goog-api-version: 2"
#          -X PUT
#          -T plussub.zip
#          -v https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID
#        env:
#          APP_ID: lpobdmdfgjokempajoobgfdnhjbjlnpm
