name: build and deploy(chrome)

on:
  push:
#    branches:
#      - master
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        target: [ "chrome", "firefox" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build:${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.target }}
          path: dist-${{ matrix.target }}/

  deploy-chrome:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-chrome
      - run: zip -r plussub.zip .
      - id: access_token
        run: |
          ACCESS_TOKEN=$(curl -s "https://accounts.google.com/o/oauth2/token" -d "client_id=$CHROME_CLIENT_ID&client_secret=$CHROME_CLIENT_SECRET&refresh_token=$CHROME_REFRESH_TOKEN&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob")
          # the following lines are only required for multi line json
          ACCESS_TOKEN="${ACCESS_TOKEN//'%'/'%25'}"
          ACCESS_TOKEN="${ACCESS_TOKEN//$'\n'/'%0A'}"
          ACCESS_TOKEN="${ACCESS_TOKEN//$'\r'/'%0D'}"
          echo "::set-output name=ACCESS_TOKEN::$ACCESS_TOKEN"
        env:
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      - run: >
          curl -s
          -H "Authorization: Bearer $ACCESS_TOKEN"
          -H "x-goog-api-version: 2"
          -X PUT
          -T plussub.zip
          -v https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID
        env:
          APP_ID: lpobdmdfgjokempajoobgfdnhjbjlnpm
          ACCESS_TOKEN: ${{ fromJson(steps.access_token.outputs.ACCESS_TOKEN).access_token }}
      - run: >
          curl -s
          -H "Authorization: Bearer $ACCESS_TOKEN"
          -H "x-goog-api-version: 2"
          -H "Content-Length: 0"
          -X POST
          -v https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID/publish
        env:
          APP_ID: lpobdmdfgjokempajoobgfdnhjbjlnpm
          ACCESS_TOKEN: ${{ fromJson(steps.access_token.outputs.ACCESS_TOKEN).access_token }}


  deploy-firefox:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-firefox
      - run: zip -r firefox.zip .
      - id: package_json
        run: |
          PACKAGE_JSON=$(cat package.json)
          # the following lines are only required for multi line json
          PACKAGE_JSON="${PACKAGE_JSON//'%'/'%25'}"
          PACKAGE_JSON="${PACKAGE_JSON//$'\n'/'%0A'}"
          PACKAGE_JSON="${PACKAGE_JSON//$'\r'/'%0D'}"
          echo "::set-output name=PACKAGE_JSON::$PACKAGE_JSON"
      - id: jwtGenerator
        uses: morzzz007/github-actions-jwt-generator@1.0.1
        with:
          secret: ${{ secrets.FIREFOX_JWT_SECRET }}
          payload: '{"iss":"${{ secrets.FIREFOX_JWT_ISSUER }}"}'
      - run: >
          curl -s
          -H "Authorization: JWT $ACCESS_TOKEN"
          -X POST
#          todo
          -F "upload=@firefox.zip"
          -F "version=$VERSION"
          -v https://addons.mozilla.org/api/v4/addons
        env:
          APP_ID: 83078104-a00b-45e2-8749-7a10af244653
          ACCESS_TOKEN: ${{ steps.jwtGenerator.outputs.token }}
          VERSION: ${{ fromJson(steps.package_json.outputs.PACKAGE_JSON).version }}
