name: build and deploy(chrome)

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        target: [ "chrome", "firefox" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build:${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.target }}
          path: dist-${{ matrix.target }}/

  deploy-chrome:
    needs:
      - build
    # if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    steps:
      - run: echo deploy

     # - run: curl -H "Authorization: Bearer $TOKEN"  -H "x-goog-api-version: 2"  -X PUT -T $FILE_NAME -v  https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID
