name: build and deploy(chrome)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build:chrome
      - run: npm run zip
      - uses: actions/upload-artifact@v2
        with:
          name: plussub-chrome.zip
          path: plussub.zip

